### ISSUE TITLE
mousewheel addEventListener attached to undefined

### ISSUE THREAD

**Issue by amsross** [rochal/jQuery-slimScroll#129]
Getting this error in Chrome on Windows:

         Uncaught TypeError: Cannot read property 'addEventListener' of undefined
         jquery.slimscroll.js:383

It looks like you're checking `window.addEventListener` on line 380, but then adding that listener to `this` on line 382, which is undefined:

          if (window.addEventListener)
          {
            this.addEventListener('DOMMouseScroll', _onWheel, false );
            this.addEventListener('mousewheel', _onWheel, false );
            this.addEventListener('MozMousePixelScroll', _onWheel, false );
          }

Perhaps this would be correct:

          if (window.addEventListener)
          {
            window.addEventListener('DOMMouseScroll', _onWheel, false );
            window.addEventListener('mousewheel', _onWheel, false );
            window.addEventListener('MozMousePixelScroll', _onWheel, false );
          }

Is this something only I'm experiencing? If not, I'll send a PR.

**Comment by rochal** [comment]
Fixed with #198
