### ISSUE TITLE
Setting default properties

### ISSUE THREAD

**Issue by clarkk** [rochal/jQuery-slimScroll#171]
Make it possible to set som default properties so you don't have to add them each time you add slimscroll to an element

**Comment by rochal** [comment]
You could do it easily be extracting the opts into a separate object that you reuse between components:

```
$myGlobalSlimScrollProperties = {
    position: 'left',
    height: '150px',
    railVisible: true,
    alwaysVisible: true
};

$('#element-one').slimScroll($myGlobalSlimScrollProperties);
$('#element-two').slimScroll($myGlobalSlimScrollProperties);
```

**Comment by clarkk** [comment]
It would be better to have a private opts inside the slimscroll so you don't pollute the global/window scope with unnessesary objects/vars
