### ISSUE TITLE
add NPM package

### ISSUE THREAD

**Issue by theofidry** [rochal/jQuery-slimScroll#173]
It would be nice to also publish it as an NPM package!

**Comment by rochal** [comment]
already in bower, I don't think it belongs in npm?

**Comment by theofidry** [comment]
npm used as much as Bower for front-end package manager. Besides when you're using a non-node application, you usually already have another package manager, Composer, Bundler, etc. So with npm it already makes 2 package managers, adding a third way for a package is a little bit... annoying.

And publishing an npm package is very similar to publishing a Bower one ;)
