### ISSUE TITLE
How to destroy the slimScroll only from parent not from children

### ISSUE THREAD

**Issue by 3gwebtrain** [rochal/jQuery-slimScroll#182]
I would like to destroy the slimScroll with the following condition, it works fine.

    if(this.spaceFinder(this.clippings)  < this.clippings.innerHeight() ) {
        this.clippings.slimScroll({destroy:true});
		//remove from all childrens too..
    }

But the issue is this is removing the all slimScroll objects from the children too.

so, parent and children all are destroyed, how to avoid that?

Here is my condition, I am not using the id I using the class selector here.
go live here:
http://jsfiddle.net/L6q58tf9/32/

**Comment by SpartakusMd** [comment]
@3gwebtrain, I made a pull request to fix this issue. You can change your jquery.slimscroll.js and have this solution implemented. Here are the changes:
````
             // find bar and rail
-            bar = me.parent().find('.' + o.barClass);
-            rail = me.parent().find('.' + o.railClass);
+            bar = me.closest('.' + o.barClass);
+            rail = me.closest('.' + o.railClass);
````

**Comment by rochal** [comment]
Thanks for your contribution @SpartakusMd!
