### ISSUE TITLE
Is there any development on this plugin?

### ISSUE THREAD

**Issue by princeofnaxos** [rochal/jQuery-slimScroll#197]
Last update is 7 months old, there are 95 open issues..... Is there any activity on this plugin?

Unmaintained plugins should not be used in production environments.

**Comment by rochal** [comment]
Yes there is.

**Comment by princeofnaxos** [comment]
Ok, good to hear. When do you expect to release a new version?

With best regards,

Edwin Boersma

*Fasterminds*
/A Marketing Company./
www.fasterminds.com <http://www.fasterminds.com>

Phone: +46 (709) 726431

Webpage: www.fasterminds.com <http://www.fasterminds.com>
Email: edwin.boersma@fasterminds.com <mailto:edwin.boersma@fasterminds.com>

This communication is intended for the person or entity to which it is 
addressed and may be confidential. Any review, re-transmission or 
dissemination is prohibited. If you received this transmission in error, 
please contact the sender then delete this message.

This email has been virus checked by the latest virus checking software, 
however, we advise you to carry out your own virus check as we cannot 
accept liability for any damage sustained as a result of any software 
viruses.

**Comment by magentapose** [comment]
It is sad such a good plugin has had no releases for 7 months! I wish you could address some of the open issues rochal... some are quite important
