### ISSUE TITLE
Jumpy scrolling in Firefox in jQuery slimScroll 1.3.3 plugin

### ISSUE THREAD

**Issue by nilacseruet** [rochal/jQuery-slimScroll#202]
I am using the jQuery SlimScroll latest version Plugin(1.3.3).

There have a div element and this element content is dynamically loaded via ajax call. I am using slimScroll on that div and tried to start from bottom. The slimscrollbar start at the bottom but the inside scrollcontent jump a little bit up.

Its work perfectly on google crome, safari, only problem in firefox. Here is my jquery code.

 $el = $('#myDiv');
 $el.slimScroll({
    height: '350px',
    start: 'bottom',
    alwaysVisible: true,
    allowPageScroll: false
});

Please help me to solve this problem.

**Comment by sferoze** [comment]
I am having the same issue
