### ISSUE TITLE
mouse wheel event on chrome

### ISSUE THREAD

**Issue by jimiwhite1020** [rochal/jQuery-slimScroll#206]
The mouse wheel scroll is not working on chrome.

I think it should use document.addEventListener('mousewheel',...) instead of window.addEventListener only for chrome.

**Comment by rochal** [comment]
hi @jimiwhite1020 , which version of Chrome? I just tested it on latest, 43.0.2357.81 m and it works fine.

**Comment by jimiwhite1020** [comment]
I tested with chrome 42.0.2311.135

http://rocha.la/jQuery-slimScroll
On this page, can you scroll the slim scrollbar areas with you mouse wheel? I can't.

**Comment by jimiwhite1020** [comment]
It was because of the damn extension: https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj?hl=en-US

It works fine once I disable it.

Thank you!
