### ISSUE TITLE
destroy doesnot remove rail and bar in 1.3.6 but works for 1.3.3

### ISSUE THREAD

**Issue by dejavu1987** [rochal/jQuery-slimScroll#216]
Please take a look at the following pen.
destroy works in 1.3.3
http://codepen.io/dejavu1987/pen/VvZmzZ?editors=001

**Comment by laomao800** [comment]
https://github.com/rochal/jQuery-slimScroll/pull/217

**Comment by dejavu1987** [comment]
Thanks @laomao800
