### ISSUE TITLE
Feature-request: Events for top/actual/bottom position

### ISSUE THREAD

**Issue by renet** [rochal/jQuery-slimScroll#24]
Hello there, thank you for your already great plug-in!

I want to add gradients to the top/bottom of my content so that it fades out, if the content is larger than the surrounding scroll-div. But I also want the top gradient to fade out, if the scrollbar reached the top, and the same for the bottom gradient. Therefore, I'd ask you to add special events like "reachedBottom" and "reachedTop" that are trown in these cases.

Alternatively (or better additionally) it would be great, to have an option for gradients being added automatically by your script (with an option to define the color, as well). But primarily I'm asking for the events as they offer more (and custom) possibilities.

There would be even more possibilities, if it was possible to get the actual position and the maximum (bottom) possition of the scrollbar (each in pixels) in an event that is thrown each time that the scrollbar changes its position. This way it would be possible (for example) to have "growing" and "shrinking" gradients at the top/bottom depending on how far away the scrollbar is from its top/bottom position. Android (at least Samsung) smartphones use this effect a lot, already.

It would be great to get some feedback whether you're planning to investigate in this features, or not. Thank you! :)

**Comment by dovanduy** [comment]
code angular_slimscroll + example
http://gool.eu.pn/index.php/?p=1miofA
