### ISSUE TITLE
please publish 1.3.8

### ISSUE THREAD

**Issue by MarkHerhold** [rochal/jQuery-slimScroll#249]
The last version on npm is 1.3.6

**Comment by hduchesn** [comment]
same for bower! please update ;)

**Comment by ukjin1192** [comment]
+1

**Comment by xmichaelx** [comment]
Well, I'll bump the issue. I need this for webpack too :smile:

**Comment by dcalde** [comment]
bump.
main is missing in bower.json for 1.3.7

**Comment by rochal** [comment]
Done, sorry for the delay.
