### ISSUE TITLE
How to listen and run something on "scroll" event?

### ISSUE THREAD

**Issue by mrfzd** [rochal/jQuery-slimScroll#258]
Basically I want to run some stuff whenever the user scrolls... how could I possibly do that?

I already know about this event which I found your website, but there is no other events other than this one;

```
..
var $scrollable = $('.scrollable');

$scrollable.slimScroll().bind('slimscroll', function (e, pos) {
    RunSomethingElse();
});
...
```

But this only works when the scrollbar reaches either top or bottom of the scrollable section.

The scrollbar itself works fine, just need an event listener!

Thank you

**Comment by baktun14** [comment]
I looked at the source code and he fires a 'slimscrolling' event when scrolling. I think it should do it.

```
$scrollable.slimScroll().bind('slimscrolling', function (e, pos) {
    RunSomethingElse();
});
```

**Comment by mrfzd** [comment]
Yes that's what I found as well, works perfectly :+1: 
This is very handy plugin but it's lacking of good documentation unfortunetly :(
Thank you
