### ISSUE TITLE
Docs site down?

### ISSUE THREAD

**Issue by JeffBeltran** [rochal/jQuery-slimScroll#277]
wondering if just bad luck today that it's down? or has it been down for awhile now?

http://rocha.la/jQuery-slimScroll

Any other documentation out there?

**Comment by JeffBeltran** [comment]
just incase someone needs it, i ended up using 

https://web.archive.org/web/20161106212933/http://rocha.la/jQuery-slimScroll/

**Comment by rochal** [comment]
Not sure what was happening, it's back online.
