### ISSUE TITLE
http://rocha.la/jQuery-slimScroll not working

### ISSUE THREAD

**Issue by fume** [rochal/jQuery-slimScroll#282]
Hi,
seems that the docs website is not working due to a DB error.

**Comment by ProxyAi** [comment]
Its still down :(

**Comment by fume** [comment]
It is from at least one week I guess

**Comment by smartcorestudio** [comment]
https://web.archive.org/web/20170219125128/http://rocha.la/jQuery-slimScroll/ 😄

**Comment by rochal** [comment]
Bad host migration :relaxed:
Fixed, thanks for reporting.
