### ISSUE TITLE
Scroll child div also scrolls the window

### ISSUE THREAD

**Issue by captain-melanie** [rochal/jQuery-slimScroll#312]
Parent div scrolls by using ```overflow: auto;``` child div scrolls by using the slim scroll. How do I prevent scrolling the parent element when the child element scrolls.

The following clip addresses the issue. 
http://recordit.co/ypbKuf0iaF

Possible solutions that I have tried but not working:
1. ```onmouseover``` and ```onmouseout``` events
```<div onmouseover="document.body.style.overflow='hidden';" onmouseout="document.body.style.overflow='auto';"></div>```

2. ```e.preventDefaut()``` on the slim scroll source code, in function ```slimScroll```

**Comment by davbpad** [comment]
Seems to work in firefox, must be a chrome issue.

**Comment by davbpad** [comment]
@captain-melanie The jquery in this answer allowed me to stop the scroll event from impacting the parent window: https://stackoverflow.com/a/16324762/6757848
