### ISSUE TITLE
Scrolling in Firefox on OS X with a trackpad also scrolls the page

### ISSUE THREAD

**Issue by paulcarey** [rochal/jQuery-slimScroll#65]
When trying to scroll the scrollable divs on http://rocha.la/jQuery-slimScroll, the page is also scrolled. 

This occurs using Firefox 20.0 on OS X 10.8.3 and the trackpad on a MacBook Air. It doesn't happen when using an external mouse, or when using Safari or Chrome.

Great plugin, I'm hoping to use it extensively.

**Comment by deiga** [comment]
@rochal Can this be reopened, since this is still an issue.

**Comment by Brilliant16** [comment]
This is still an issue. When I apply this line 
target.addEventListener('MozMousePixelScroll', _onWheel, false);

so Scroll behave Jumpy to go bottom.  unexpected behavior. this fixed issue trackpad scrolling but create Jump problem

https://github.com/rochal/jQuery-slimScroll/issues/95#issuecomment-382622589
