### ISSUE TITLE
Destroy - Can actually create a slimScroller

### ISSUE THREAD

**Issue by robly** [rochal/jQuery-slimScroll#87]
You should place a check at line 152 in-case 'destroy' is passed in as an option so that it will not accidentally create a new slimScroller if one does not already exist.

Example: If you call slimScroll({destroy: true}); 2x it will create the scroller using the default values.

There might be a better place to put it, but that seems reasonable to me glancing at it.

**Comment by abhishekyadav9590** [comment]
its not solved yet
