### ISSUE TITLE
slimScroll with jQuery sortable

### ISSUE THREAD

**Issue by jland006** [rochal/jQuery-slimScroll#89]
Hi,
Having trouble using the slimScroll plugin at the same time as jQuery sortable plugin. My goal is to be able to drag from one list box to another. When using slimScroll with my draggable list item, the list item goes under all objects when I drag it. I found this to be because of the position: relative on the slimScrollDiv. If I remove this property then I can drag on top however this messes up to positioning of the scroll bar. I have found a work around but there has to be a better way. I basically destroy the slimScroll object before I drag, then reinitialize it when I'm finished dragging. Here is an example: http://www.itstennistime.com/slimscroll/

Please tell me if there is a better way to achieve what I want. Thank you

Edit:
Another solution I've found is to use this:
scroller.css('position', '');
scroller.children('.slimScrollBar').css('width', '0px');
scroller.children('.slimScrollRail').css('width', '0px');
then to return it:
scroller.css('position', 'relative');
scroller.children('.slimScrollBar').css('width', '8px');
scroller.children('.slimScrollRail').css('width', '8px');

Any help would be appreciated. Thank you

**Comment by sahilweb6** [comment]
whats your solution?
