### ISSUE TITLE
Scroll speed in Firefox 23

### ISSUE THREAD

**Issue by ghost** [rochal/jQuery-slimScroll#95]
I have problem with scroll speed. Its abnormal too fast in firefox with default wheelStep: 20

On your preview page this bug exists as well. And my friend with firefox have problems too.

In chrome, for example, its normal.

**Comment by Brilliant16** [comment]
I've read Issue-65 & this Issue-95
Both issue has solution of different bugs. Issue-65 fix issue but create a bug in Issue-95
and issue-95 reverts Issue-65

so any one has actual solution of Issue-65. I've also commented on Issue-65
https://github.com/rochal/jQuery-slimScroll/issues/65#issuecomment-379226668
